### PR TITLE
Added Secrets for WiFi credentials.

### PR DESCRIPTION
**Pull request by spoetnik**
Added Secrets file for WiFi credentials.

### CODE REVIEW

**Comment by DavyLandman** [comment]
Thanks, I wanted to avoid anyone committing that file, so that is why I explicitly added it to the .gitignore. 

What do you think about making this into to a `secret_template.h` file?  And extend the README.md?

**Comment by spoetnik** [comment]
aaah, I didn't notice the .gitignore. Either way, the defaults didn't build, and the readme wasn't clear so i thought i fixed it this way. You solution with a template-file and clear directions in the readme would be even better I think.

Thanks for this repo by the way.

**Comment by DavyLandman** [comment]
Did it work for you?

**Comment by spoetnik** [comment]
> Did it work for you?

Yes! Uninstalled Mosquitto, as it was only needed for receiving messages from the P1 meter.

**Comment by DavyLandman** [comment]
Thanks, happy to hear I've helped more than just myself.

Also thanks for updating the PR, merged it 👌🏼

**Pull request merged**
